// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerDashboard.Data;

#nullable disable

namespace PlayerDashboard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115030007_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PlayerDashboard.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 8, 14, 10, 54, 0, 0, DateTimeKind.Unspecified),
                            Duration = 239,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3600,
                            Won = false
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 8, 15, 16, 49, 0, 0, DateTimeKind.Unspecified),
                            Duration = 82,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1600,
                            Won = true
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 8, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 118,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2900,
                            Won = true
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 8, 17, 16, 26, 0, 0, DateTimeKind.Unspecified),
                            Duration = 119,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2200,
                            Won = false
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 8, 18, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            Duration = 53,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 4000,
                            Won = true
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 8, 19, 15, 7, 0, 0, DateTimeKind.Unspecified),
                            Duration = 59,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3700,
                            Won = true
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 8, 20, 16, 46, 0, 0, DateTimeKind.Unspecified),
                            Duration = 134,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2200,
                            Won = true
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 8, 21, 12, 8, 0, 0, DateTimeKind.Unspecified),
                            Duration = 198,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1200,
                            Won = true
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 8, 22, 15, 31, 0, 0, DateTimeKind.Unspecified),
                            Duration = 51,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1900,
                            Won = true
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 8, 23, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            Duration = 147,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3700,
                            Won = false
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 8, 24, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Duration = 50,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2800,
                            Won = true
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2024, 8, 25, 10, 4, 0, 0, DateTimeKind.Unspecified),
                            Duration = 119,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3100,
                            Won = false
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2024, 8, 26, 10, 29, 0, 0, DateTimeKind.Unspecified),
                            Duration = 71,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3000,
                            Won = true
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2024, 8, 27, 17, 25, 0, 0, DateTimeKind.Unspecified),
                            Duration = 92,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1200,
                            Won = false
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2024, 8, 28, 17, 49, 0, 0, DateTimeKind.Unspecified),
                            Duration = 93,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1100,
                            Won = false
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2024, 8, 29, 15, 2, 0, 0, DateTimeKind.Unspecified),
                            Duration = 128,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1300,
                            Won = false
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2024, 8, 30, 16, 42, 0, 0, DateTimeKind.Unspecified),
                            Duration = 203,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1600,
                            Won = true
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2024, 8, 31, 15, 48, 0, 0, DateTimeKind.Unspecified),
                            Duration = 239,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3500,
                            Won = true
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2024, 9, 1, 12, 48, 0, 0, DateTimeKind.Unspecified),
                            Duration = 160,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2500,
                            Won = false
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2024, 9, 2, 16, 37, 0, 0, DateTimeKind.Unspecified),
                            Duration = 107,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2100,
                            Won = false
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2024, 9, 3, 16, 28, 0, 0, DateTimeKind.Unspecified),
                            Duration = 225,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3600,
                            Won = false
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2024, 9, 4, 16, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 229,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2600,
                            Won = false
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2024, 9, 5, 17, 46, 0, 0, DateTimeKind.Unspecified),
                            Duration = 52,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3600,
                            Won = false
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2024, 9, 6, 12, 25, 0, 0, DateTimeKind.Unspecified),
                            Duration = 38,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2400,
                            Won = false
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2024, 9, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 70,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3100,
                            Won = true
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2024, 9, 8, 11, 53, 0, 0, DateTimeKind.Unspecified),
                            Duration = 188,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1000,
                            Won = true
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2024, 9, 9, 15, 34, 0, 0, DateTimeKind.Unspecified),
                            Duration = 58,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 4000,
                            Won = false
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2024, 9, 10, 11, 11, 0, 0, DateTimeKind.Unspecified),
                            Duration = 160,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2400,
                            Won = false
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2024, 9, 11, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            Duration = 162,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3200,
                            Won = true
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2024, 9, 12, 14, 4, 0, 0, DateTimeKind.Unspecified),
                            Duration = 50,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1100,
                            Won = false
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2024, 9, 13, 14, 13, 0, 0, DateTimeKind.Unspecified),
                            Duration = 122,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1000,
                            Won = false
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2024, 9, 14, 14, 52, 0, 0, DateTimeKind.Unspecified),
                            Duration = 219,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1900,
                            Won = false
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2024, 9, 15, 16, 7, 0, 0, DateTimeKind.Unspecified),
                            Duration = 231,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1800,
                            Won = false
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2024, 9, 16, 12, 43, 0, 0, DateTimeKind.Unspecified),
                            Duration = 130,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3700,
                            Won = false
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2024, 9, 17, 10, 28, 0, 0, DateTimeKind.Unspecified),
                            Duration = 188,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1500,
                            Won = false
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2024, 9, 18, 17, 7, 0, 0, DateTimeKind.Unspecified),
                            Duration = 81,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3300,
                            Won = false
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2024, 9, 19, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Duration = 171,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3900,
                            Won = true
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2024, 9, 20, 12, 18, 0, 0, DateTimeKind.Unspecified),
                            Duration = 78,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 4000,
                            Won = true
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2024, 9, 21, 12, 46, 0, 0, DateTimeKind.Unspecified),
                            Duration = 104,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1800,
                            Won = false
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2024, 9, 22, 12, 59, 0, 0, DateTimeKind.Unspecified),
                            Duration = 50,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3700,
                            Won = false
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2024, 9, 23, 11, 32, 0, 0, DateTimeKind.Unspecified),
                            Duration = 192,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1600,
                            Won = false
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2024, 9, 24, 16, 54, 0, 0, DateTimeKind.Unspecified),
                            Duration = 93,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3700,
                            Won = false
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2024, 9, 25, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            Duration = 117,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2200,
                            Won = false
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2024, 9, 26, 13, 22, 0, 0, DateTimeKind.Unspecified),
                            Duration = 142,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2900,
                            Won = false
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2024, 9, 27, 17, 4, 0, 0, DateTimeKind.Unspecified),
                            Duration = 41,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2600,
                            Won = true
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2024, 9, 28, 17, 2, 0, 0, DateTimeKind.Unspecified),
                            Duration = 139,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3800,
                            Won = true
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2024, 9, 29, 11, 6, 0, 0, DateTimeKind.Unspecified),
                            Duration = 217,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2200,
                            Won = true
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2024, 9, 30, 12, 2, 0, 0, DateTimeKind.Unspecified),
                            Duration = 180,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3000,
                            Won = false
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2024, 10, 1, 14, 46, 0, 0, DateTimeKind.Unspecified),
                            Duration = 39,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2000,
                            Won = false
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2024, 10, 2, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            Duration = 50,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3800,
                            Won = false
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2024, 10, 3, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Duration = 183,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3000,
                            Won = false
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2024, 10, 4, 17, 53, 0, 0, DateTimeKind.Unspecified),
                            Duration = 201,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2100,
                            Won = false
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2024, 10, 5, 17, 49, 0, 0, DateTimeKind.Unspecified),
                            Duration = 131,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3900,
                            Won = true
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2024, 10, 6, 10, 52, 0, 0, DateTimeKind.Unspecified),
                            Duration = 194,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1100,
                            Won = true
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2024, 10, 7, 15, 19, 0, 0, DateTimeKind.Unspecified),
                            Duration = 158,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1000,
                            Won = false
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2024, 10, 8, 16, 8, 0, 0, DateTimeKind.Unspecified),
                            Duration = 56,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2600,
                            Won = true
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2024, 10, 9, 15, 6, 0, 0, DateTimeKind.Unspecified),
                            Duration = 217,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2200,
                            Won = false
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2024, 10, 10, 12, 46, 0, 0, DateTimeKind.Unspecified),
                            Duration = 155,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3900,
                            Won = false
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2024, 10, 11, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            Duration = 63,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3000,
                            Won = false
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2024, 10, 12, 16, 3, 0, 0, DateTimeKind.Unspecified),
                            Duration = 225,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2800,
                            Won = true
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2024, 10, 13, 15, 37, 0, 0, DateTimeKind.Unspecified),
                            Duration = 91,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1900,
                            Won = true
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2024, 10, 14, 11, 56, 0, 0, DateTimeKind.Unspecified),
                            Duration = 49,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3100,
                            Won = false
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2024, 10, 15, 14, 9, 0, 0, DateTimeKind.Unspecified),
                            Duration = 66,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3500,
                            Won = true
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2024, 10, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 74,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1900,
                            Won = true
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2024, 10, 17, 10, 24, 0, 0, DateTimeKind.Unspecified),
                            Duration = 43,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1700,
                            Won = true
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2024, 10, 18, 12, 29, 0, 0, DateTimeKind.Unspecified),
                            Duration = 126,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1300,
                            Won = false
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2024, 10, 19, 15, 49, 0, 0, DateTimeKind.Unspecified),
                            Duration = 85,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2700,
                            Won = true
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2024, 10, 20, 14, 50, 0, 0, DateTimeKind.Unspecified),
                            Duration = 39,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3300,
                            Won = true
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2024, 10, 21, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 223,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3100,
                            Won = false
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2024, 10, 22, 11, 55, 0, 0, DateTimeKind.Unspecified),
                            Duration = 111,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2200,
                            Won = false
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2024, 10, 23, 13, 40, 0, 0, DateTimeKind.Unspecified),
                            Duration = 139,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1600,
                            Won = true
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2024, 10, 24, 16, 6, 0, 0, DateTimeKind.Unspecified),
                            Duration = 203,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1600,
                            Won = false
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2024, 10, 25, 16, 12, 0, 0, DateTimeKind.Unspecified),
                            Duration = 99,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3400,
                            Won = true
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2024, 10, 26, 15, 58, 0, 0, DateTimeKind.Unspecified),
                            Duration = 213,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3500,
                            Won = false
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2024, 10, 27, 15, 57, 0, 0, DateTimeKind.Unspecified),
                            Duration = 48,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2600,
                            Won = false
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2024, 10, 28, 15, 29, 0, 0, DateTimeKind.Unspecified),
                            Duration = 128,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1500,
                            Won = false
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2024, 10, 29, 12, 51, 0, 0, DateTimeKind.Unspecified),
                            Duration = 223,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3400,
                            Won = true
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2024, 10, 30, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            Duration = 186,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3200,
                            Won = false
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2024, 10, 31, 12, 4, 0, 0, DateTimeKind.Unspecified),
                            Duration = 33,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1800,
                            Won = false
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2024, 11, 1, 16, 6, 0, 0, DateTimeKind.Unspecified),
                            Duration = 41,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2700,
                            Won = true
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2024, 11, 2, 11, 26, 0, 0, DateTimeKind.Unspecified),
                            Duration = 231,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1800,
                            Won = true
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2024, 11, 3, 11, 49, 0, 0, DateTimeKind.Unspecified),
                            Duration = 38,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 4000,
                            Won = false
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2024, 11, 4, 15, 58, 0, 0, DateTimeKind.Unspecified),
                            Duration = 139,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 4000,
                            Won = true
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2024, 11, 5, 13, 59, 0, 0, DateTimeKind.Unspecified),
                            Duration = 191,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3800,
                            Won = true
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2024, 11, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 162,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2900,
                            Won = true
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2024, 11, 7, 11, 18, 0, 0, DateTimeKind.Unspecified),
                            Duration = 215,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2500,
                            Won = false
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2024, 11, 8, 16, 39, 0, 0, DateTimeKind.Unspecified),
                            Duration = 37,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1100,
                            Won = false
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2024, 11, 9, 11, 6, 0, 0, DateTimeKind.Unspecified),
                            Duration = 50,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1700,
                            Won = true
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2024, 11, 10, 16, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 49,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2600,
                            Won = false
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2024, 11, 11, 15, 11, 0, 0, DateTimeKind.Unspecified),
                            Duration = 169,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2400,
                            Won = true
                        });
                });

            modelBuilder.Entity("PlayerDashboard.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AccountCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AverageGameTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPlaytimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountCreatedDate = new DateOnly(2024, 8, 14),
                            AverageGameTimeMinutes = 126,
                            DateOfBirth = new DateOnly(2008, 8, 10),
                            DisplayName = "ProGamer123",
                            EmailAddress = "john.smith@microsoft.com",
                            Level = 120,
                            TotalGames = 90,
                            TotalPlaytimeMinutes = 11362,
                            TotalWins = 39
                        });
                });

            modelBuilder.Entity("PlayerDashboard.Models.GameSession", b =>
                {
                    b.HasOne("PlayerDashboard.Models.Player", "Player")
                        .WithMany("GameSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlayerDashboard.Models.Player", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
