// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerDashboard.Data;

#nullable disable

namespace PlayerDashboard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115051717_AddAvatarUrl")]
    partial class AddAvatarUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PlayerDashboard.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 8, 15, 17, 25, 0, 0, DateTimeKind.Unspecified),
                            Duration = 44,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 4000,
                            Won = false
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 8, 16, 13, 1, 0, 0, DateTimeKind.Unspecified),
                            Duration = 147,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2700,
                            Won = false
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 8, 17, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Duration = 170,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2600,
                            Won = false
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 8, 18, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Duration = 137,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1900,
                            Won = true
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 8, 19, 16, 29, 0, 0, DateTimeKind.Unspecified),
                            Duration = 113,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3400,
                            Won = true
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 8, 20, 13, 42, 0, 0, DateTimeKind.Unspecified),
                            Duration = 150,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 4000,
                            Won = true
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 8, 21, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            Duration = 74,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2700,
                            Won = false
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 8, 22, 11, 25, 0, 0, DateTimeKind.Unspecified),
                            Duration = 80,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1800,
                            Won = true
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 8, 23, 13, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 93,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2700,
                            Won = true
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 8, 24, 17, 18, 0, 0, DateTimeKind.Unspecified),
                            Duration = 37,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2600,
                            Won = true
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 8, 25, 17, 51, 0, 0, DateTimeKind.Unspecified),
                            Duration = 76,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1600,
                            Won = true
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2024, 8, 26, 17, 36, 0, 0, DateTimeKind.Unspecified),
                            Duration = 37,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1300,
                            Won = true
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2024, 8, 27, 14, 19, 0, 0, DateTimeKind.Unspecified),
                            Duration = 64,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1600,
                            Won = false
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2024, 8, 28, 15, 16, 0, 0, DateTimeKind.Unspecified),
                            Duration = 216,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1200,
                            Won = true
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2024, 8, 29, 15, 4, 0, 0, DateTimeKind.Unspecified),
                            Duration = 212,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3200,
                            Won = false
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2024, 8, 30, 16, 39, 0, 0, DateTimeKind.Unspecified),
                            Duration = 122,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3700,
                            Won = true
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2024, 8, 31, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            Duration = 217,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3100,
                            Won = true
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2024, 9, 1, 11, 57, 0, 0, DateTimeKind.Unspecified),
                            Duration = 68,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2400,
                            Won = true
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2024, 9, 2, 10, 49, 0, 0, DateTimeKind.Unspecified),
                            Duration = 49,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 4000,
                            Won = true
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2024, 9, 3, 10, 24, 0, 0, DateTimeKind.Unspecified),
                            Duration = 60,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1700,
                            Won = false
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2024, 9, 4, 14, 3, 0, 0, DateTimeKind.Unspecified),
                            Duration = 76,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2900,
                            Won = true
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2024, 9, 5, 15, 43, 0, 0, DateTimeKind.Unspecified),
                            Duration = 166,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1300,
                            Won = false
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2024, 9, 6, 13, 51, 0, 0, DateTimeKind.Unspecified),
                            Duration = 169,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3300,
                            Won = false
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2024, 9, 7, 10, 18, 0, 0, DateTimeKind.Unspecified),
                            Duration = 44,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1100,
                            Won = false
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2024, 9, 8, 13, 35, 0, 0, DateTimeKind.Unspecified),
                            Duration = 82,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3800,
                            Won = false
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2024, 9, 9, 13, 39, 0, 0, DateTimeKind.Unspecified),
                            Duration = 31,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2300,
                            Won = true
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2024, 9, 10, 17, 35, 0, 0, DateTimeKind.Unspecified),
                            Duration = 223,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3900,
                            Won = false
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2024, 9, 11, 11, 51, 0, 0, DateTimeKind.Unspecified),
                            Duration = 153,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1400,
                            Won = true
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2024, 9, 12, 10, 23, 0, 0, DateTimeKind.Unspecified),
                            Duration = 60,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2100,
                            Won = false
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2024, 9, 13, 12, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 54,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1300,
                            Won = true
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2024, 9, 14, 10, 47, 0, 0, DateTimeKind.Unspecified),
                            Duration = 120,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1600,
                            Won = false
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2024, 9, 15, 10, 42, 0, 0, DateTimeKind.Unspecified),
                            Duration = 191,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3200,
                            Won = false
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2024, 9, 16, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Duration = 70,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3500,
                            Won = false
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2024, 9, 17, 14, 1, 0, 0, DateTimeKind.Unspecified),
                            Duration = 69,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1700,
                            Won = true
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2024, 9, 18, 14, 53, 0, 0, DateTimeKind.Unspecified),
                            Duration = 215,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2200,
                            Won = true
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2024, 9, 19, 11, 24, 0, 0, DateTimeKind.Unspecified),
                            Duration = 99,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3500,
                            Won = true
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2024, 9, 20, 10, 57, 0, 0, DateTimeKind.Unspecified),
                            Duration = 79,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3000,
                            Won = true
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2024, 9, 21, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            Duration = 173,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1300,
                            Won = false
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2024, 9, 22, 10, 26, 0, 0, DateTimeKind.Unspecified),
                            Duration = 183,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2600,
                            Won = false
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2024, 9, 23, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 176,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2300,
                            Won = false
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2024, 9, 24, 11, 18, 0, 0, DateTimeKind.Unspecified),
                            Duration = 131,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3100,
                            Won = true
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2024, 9, 25, 12, 51, 0, 0, DateTimeKind.Unspecified),
                            Duration = 101,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3600,
                            Won = true
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2024, 9, 26, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Duration = 90,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1900,
                            Won = true
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2024, 9, 27, 13, 21, 0, 0, DateTimeKind.Unspecified),
                            Duration = 181,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2600,
                            Won = false
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2024, 9, 28, 14, 47, 0, 0, DateTimeKind.Unspecified),
                            Duration = 46,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1300,
                            Won = true
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2024, 9, 29, 17, 17, 0, 0, DateTimeKind.Unspecified),
                            Duration = 187,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1500,
                            Won = false
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2024, 9, 30, 11, 57, 0, 0, DateTimeKind.Unspecified),
                            Duration = 216,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1400,
                            Won = false
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2024, 10, 1, 15, 22, 0, 0, DateTimeKind.Unspecified),
                            Duration = 144,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2900,
                            Won = false
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2024, 10, 2, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            Duration = 187,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2900,
                            Won = false
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2024, 10, 3, 15, 29, 0, 0, DateTimeKind.Unspecified),
                            Duration = 111,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3800,
                            Won = false
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2024, 10, 4, 12, 47, 0, 0, DateTimeKind.Unspecified),
                            Duration = 93,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1800,
                            Won = false
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2024, 10, 5, 17, 32, 0, 0, DateTimeKind.Unspecified),
                            Duration = 166,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3400,
                            Won = false
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2024, 10, 6, 17, 37, 0, 0, DateTimeKind.Unspecified),
                            Duration = 49,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1100,
                            Won = false
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2024, 10, 7, 17, 57, 0, 0, DateTimeKind.Unspecified),
                            Duration = 99,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3900,
                            Won = true
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2024, 10, 8, 12, 22, 0, 0, DateTimeKind.Unspecified),
                            Duration = 152,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2500,
                            Won = true
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2024, 10, 9, 15, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 33,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3100,
                            Won = true
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2024, 10, 10, 15, 1, 0, 0, DateTimeKind.Unspecified),
                            Duration = 103,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1100,
                            Won = true
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2024, 10, 11, 10, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 191,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3700,
                            Won = false
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2024, 10, 12, 13, 22, 0, 0, DateTimeKind.Unspecified),
                            Duration = 93,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1000,
                            Won = true
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2024, 10, 13, 15, 54, 0, 0, DateTimeKind.Unspecified),
                            Duration = 183,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1500,
                            Won = true
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2024, 10, 14, 12, 58, 0, 0, DateTimeKind.Unspecified),
                            Duration = 168,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3500,
                            Won = true
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2024, 10, 15, 16, 13, 0, 0, DateTimeKind.Unspecified),
                            Duration = 56,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2800,
                            Won = true
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2024, 10, 16, 14, 36, 0, 0, DateTimeKind.Unspecified),
                            Duration = 57,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3300,
                            Won = false
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2024, 10, 17, 16, 16, 0, 0, DateTimeKind.Unspecified),
                            Duration = 103,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1600,
                            Won = true
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2024, 10, 18, 10, 54, 0, 0, DateTimeKind.Unspecified),
                            Duration = 54,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2700,
                            Won = false
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2024, 10, 19, 10, 12, 0, 0, DateTimeKind.Unspecified),
                            Duration = 142,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2900,
                            Won = false
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2024, 10, 20, 10, 13, 0, 0, DateTimeKind.Unspecified),
                            Duration = 125,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1300,
                            Won = true
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2024, 10, 21, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Duration = 71,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3300,
                            Won = false
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2024, 10, 22, 17, 47, 0, 0, DateTimeKind.Unspecified),
                            Duration = 89,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 3500,
                            Won = false
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2024, 10, 23, 10, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 76,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1400,
                            Won = true
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2024, 10, 24, 15, 23, 0, 0, DateTimeKind.Unspecified),
                            Duration = 49,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3000,
                            Won = false
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2024, 10, 25, 14, 3, 0, 0, DateTimeKind.Unspecified),
                            Duration = 205,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2200,
                            Won = false
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2024, 10, 26, 13, 33, 0, 0, DateTimeKind.Unspecified),
                            Duration = 139,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 1800,
                            Won = true
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2024, 10, 27, 14, 2, 0, 0, DateTimeKind.Unspecified),
                            Duration = 45,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 3600,
                            Won = true
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2024, 10, 28, 11, 46, 0, 0, DateTimeKind.Unspecified),
                            Duration = 228,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3100,
                            Won = true
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2024, 10, 29, 15, 49, 0, 0, DateTimeKind.Unspecified),
                            Duration = 55,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2700,
                            Won = true
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2024, 10, 30, 12, 34, 0, 0, DateTimeKind.Unspecified),
                            Duration = 98,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2200,
                            Won = false
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2024, 10, 31, 16, 55, 0, 0, DateTimeKind.Unspecified),
                            Duration = 112,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1500,
                            Won = true
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2024, 11, 1, 14, 31, 0, 0, DateTimeKind.Unspecified),
                            Duration = 145,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2000,
                            Won = true
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2024, 11, 2, 15, 51, 0, 0, DateTimeKind.Unspecified),
                            Duration = 129,
                            GameMode = 0,
                            PlayerId = 1,
                            Score = 2900,
                            Won = true
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2024, 11, 3, 11, 7, 0, 0, DateTimeKind.Unspecified),
                            Duration = 40,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2100,
                            Won = true
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2024, 11, 4, 13, 28, 0, 0, DateTimeKind.Unspecified),
                            Duration = 113,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1500,
                            Won = false
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2024, 11, 5, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            Duration = 70,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2600,
                            Won = false
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2024, 11, 6, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            Duration = 86,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 2800,
                            Won = false
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2024, 11, 7, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            Duration = 178,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2600,
                            Won = true
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2024, 11, 8, 11, 56, 0, 0, DateTimeKind.Unspecified),
                            Duration = 115,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2600,
                            Won = true
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2024, 11, 9, 13, 18, 0, 0, DateTimeKind.Unspecified),
                            Duration = 86,
                            GameMode = 1,
                            PlayerId = 1,
                            Score = 1800,
                            Won = false
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2024, 11, 10, 14, 58, 0, 0, DateTimeKind.Unspecified),
                            Duration = 89,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 1500,
                            Won = false
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2024, 11, 11, 13, 39, 0, 0, DateTimeKind.Unspecified),
                            Duration = 70,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 2300,
                            Won = true
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2024, 11, 12, 10, 46, 0, 0, DateTimeKind.Unspecified),
                            Duration = 82,
                            GameMode = 2,
                            PlayerId = 1,
                            Score = 3000,
                            Won = false
                        });
                });

            modelBuilder.Entity("PlayerDashboard.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AccountCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("AverageGameTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPlaytimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountCreatedDate = new DateOnly(2024, 8, 15),
                            AvatarUrl = "https://cdn.jsdelivr.net/gh/alohe/memojis/png/upstream_17.png",
                            AverageGameTimeMinutes = 113,
                            DateOfBirth = new DateOnly(2008, 8, 10),
                            DisplayName = "ProGamer123",
                            EmailAddress = "john.smith@microsoft.com",
                            Level = 120,
                            TotalGames = 90,
                            TotalPlaytimeMinutes = 10230,
                            TotalWins = 47
                        });
                });

            modelBuilder.Entity("PlayerDashboard.Models.GameSession", b =>
                {
                    b.HasOne("PlayerDashboard.Models.Player", "Player")
                        .WithMany("GameSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlayerDashboard.Models.Player", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
